a = int(input("Zadaj cislo a: "))
b = int(input("Zadaj cislo a: "))
print(f"Dobry den pan {a}")
print(f"Sucet cislic je {a + b}")
print(f"Sucin cislic je {a*b}")
print("This was added in the browser")
